### ISSUE TITLE
Issue with Apostrophes

### ISSUE THREAD

**Issue by Jobebo** [janw/letterboxd-watchlist-rss#1]
Hi!  I've been trying to use your watchlist2rss.py file but i get the following error when it grabs a title with apostrophes:
Adding 28 movies from page 1
Woman at War (2018)
Keep an Eye Out (2018)
Possibly in Michigan (1983)
Minding the Gap (2018)
Trust (2018)
Parsing failed
Traceback (most recent call last):
  File "watchlist2rss.py", line 77, in <module>
    main()
  File "watchlist2rss.py", line 62, in main
    movie_description = movie_description.text.strip()
AttributeError: 'NoneType' object has no attribute 'text'

In that case it seems to fail on the movie: "Avant qu'on explose"
Tried it on a list with no french titles and it worked fine.
Link: https://letterboxd.com/jimmyblux/watchlist/

Thanks for your help!

Jobebo

**Comment by janw** [comment]
Seems to be fixed in 0.2.0. Cheers!
